name: base
description: Base app.

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  build_runner: any
  crypted_preferences: ^0.0.2
  flutter_secure_storage: ^3.3.3
  uuid: ^2.2.0
  url_launcher: ^5.5.0
  easy_localization: ^2.3.2
  flutter_bloc: ^5.0.1
  equatable: ^1.2.2
  flutter_cache_manager: ^1.1.3
  flutter_markdown: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  mockito: ^4.1.1

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
